<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*;node_modules/**;Deployment/**</DefaultItemExcludes>

    <ThemesDirectory>../../../../../</ThemesDirectory>
    <LombiqHelpfulExtensionsPath>$(ThemesDirectory)../Modules/Lombiq.HelpfulExtensions/Lombiq.HelpfulExtensions/Lombiq.HelpfulExtensions.csproj</LombiqHelpfulExtensionsPath>
    <LombiqNodeJsExtensionsDirectory>$(ThemesDirectory)../Utilities/Lombiq.NodeJs.Extensions/Lombiq.NodeJs.Extensions/</LombiqNodeJsExtensionsDirectory>
    <LombiqNodeJsExtensionsPath>$(LombiqNodeJsExtensionsDirectory)Lombiq.NodeJs.Extensions.csproj</LombiqNodeJsExtensionsPath>
    <LombiqHostingMediaThemePath>$(ThemesDirectory)Lombiq.Hosting.MediaTheme/Lombiq.Hosting.MediaTheme/Lombiq.Hosting.MediaTheme.csproj</LombiqHostingMediaThemePath>
    <LombiqHostingMediaThemeTargetsProps>$(ThemesDirectory)Lombiq.Hosting.MediaTheme/Lombiq.Hosting.MediaTheme.Targets/Lombiq.Hosting.MediaTheme.Targets.props</LombiqHostingMediaThemeTargetsProps>
    <LombiqHostingMediaThemeTargetsTargets>$(ThemesDirectory)Lombiq.Hosting.MediaTheme/Lombiq.Hosting.MediaTheme.Targets/Lombiq.Hosting.MediaTheme.Targets.targets</LombiqHostingMediaThemeTargetsTargets>

    <MediaThemeBaseId>Lombiq.BaseTheme</MediaThemeBaseId>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../Readme.md" />
    <Content Include=".config/dotnet-tools.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Theme.Targets" Version="$(OrchardCoreVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true' and Exists($(LombiqHelpfulExtensionsPath))">
    <ProjectReference Include="$(LombiqHelpfulExtensionsPath)" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true' and Exists($(LombiqNodeJsExtensionsPath))">
    <ProjectReference Include="$(LombiqNodeJsExtensionsPath)" />
  </ItemGroup>

  <ImportGroup Condition="'$(NuGetBuild)' != 'true' and Exists($(LombiqNodeJsExtensionsPath))">
    <Import Project="$(LombiqNodeJsExtensionsDirectory)Lombiq.NodeJs.Extensions.props" />
    <Import Project="$(LombiqNodeJsExtensionsDirectory)Lombiq.NodeJs.Extensions.targets" />
  </ImportGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true' or !Exists($(LombiqHelpfulExtensionsPath))">
    <PackageReference Include="Lombiq.HelpfulExtensions" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true' or !Exists($(LombiqNodeJsExtensionsPath))">
    <PackageReference Include="Lombiq.NodeJs.Extensions" Version="3.0.1-alpha.3.nest-608" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Condition="Exists($(LombiqHostingMediaThemePath))" Include="$(LombiqHostingMediaThemePath)" />
    <PackageReference Condition="!Exists($(LombiqHostingMediaThemePath))" Include="Lombiq.Hosting.MediaTheme" Version="9.0.1-alpha.0.osoe-925" />
    <PackageReference Condition="!Exists($(LombiqHostingMediaThemeTargetsProps))" Include="Lombiq.Hosting.MediaTheme.Targets" Version="9.0.1-alpha.0.osoe-925" />
  </ItemGroup>

  <Import Condition="Exists($(LombiqHostingMediaThemeTargetsProps))" Project="$(LombiqHostingMediaThemeTargetsProps)" />
  <Import Condition="Exists($(LombiqHostingMediaThemeTargetsTargets))" Project="$(LombiqHostingMediaThemeTargetsTargets)" />

  <!-- Overriding to change the dependency order of the targets. -->
  <Target Name="MediaThemeDeploymentBeforeTargets" BeforeTargets="EmbeddModuleAssets;OrchardCoreEmbedModuleAssets" />
  <Target Name="MediaThemeDeploymentAfterTargets" AfterTargets="NpmDotnetPrebuild" />
</Project>
