name: Validate Pull Request

on:
  pull_request_target:

jobs:
  validate-pull-request:
    name: Validate Pull Request
    uses: Lombiq/GitHub-Actions/.github/workflows/validate-submodule-pull-request.yml@dev
    secrets:
      PARENT_TOKEN: ${{ secrets.LOMBIQBOT_GITHUB_PERSONAL_ACCESS_TOKEN }}
    with:
      repository: Lombiq/DotNest-Core-Sites-SDK
